import type { ProductRecord, ProductFormState } from "../types/products.types";
import { moneyInput } from "./moneyInput";


export const emptyForm: ProductFormState = {
  name: "",
  sale_price: "",
  cost_price: "",
  purchase_price: "",
  sku: "",
  barcode: "",
  category_id: "",
  unit: "UN",
  minimum_stock: "0",
  maximum_stock: "",
  current_stock: "0",
  active: 1,
  ncm: "",
  cfop: "",
  origin: "",
  cest: "",
  notes: "",
  situation: "",
  supplier_code: "",
  supplier_name: "",
  location: "",
  brand: "",
  product_group: "",
  short_description: "",
  complementary_description: "",
  additional_info: "",
  department: "",
  item_type: "Produto",
  expiration_date: "",
  items_per_box: "",
  packaging_barcode: "",
  production_type: "",
  ipi_tax_class: "",
  fci_number: "",
  supplier_product_description: "",
  supplier_warranty_months: "",
  net_weight_kg: "",
  gross_weight_kg: "",
  width_cm: "",
  height_cm: "",
  depth_cm: "",
  volumes: "",
  is_variation: 0,
  parent_code: "",
  product_condition: "",
  tags: "",
  tags_group: "",
};


export function recordToForm(product: ProductRecord): ProductFormState {
  return {
    ...emptyForm,
    name: product.nome ?? "",
    sale_price: moneyInput(product.preco_venda),
    cost_price: moneyInput(product.preco_custo),
    purchase_price: moneyInput(product.preco_compra ?? 0),
    sku: product.sku ?? "",
    barcode: product.codigo_barras ?? "",
    category_id: product.categoria_id ?? "",
    unit: product.unidade_medida ?? product.measurement_unit ?? "UN",
    minimum_stock: String(product.estoque_minimo ?? 0),
    maximum_stock: product.estoque_maximo === null || product.estoque_maximo === undefined ? "" : String(product.estoque_maximo),
    current_stock: String(product.estoque_atual ?? 0),
    active: Number(product.ativo ?? 1),
    ncm: product.ncm ?? "",
    cfop: product.cfop ?? "",
    origin: product.origem ?? "",
    cest: product.cest ?? "",
    notes: product.observacoes ?? "",
    situation: product.situacao ?? "",
    supplier_code: product.supplier_code ?? "",
    supplier_name: product.supplier_name ?? "",
    location: product.localizacao ?? "",
    brand: product.brand ?? product.marca ?? "",
    product_group: product.product_group ?? "",
    short_description: product.short_description ?? "",
    complementary_description: product.complementary_description ?? "",
    additional_info: product.additional_info ?? "",
    department: product.department ?? "",
    item_type: product.item_type ?? "Produto",
    expiration_date: product.expiration_date ?? "",
    items_per_box: product.items_per_box ? String(product.items_per_box) : "",
    packaging_barcode: product.packaging_barcode ?? "",
    production_type: product.production_type ?? "",
    ipi_tax_class: product.ipi_tax_class ?? "",
    fci_number: product.fci_number ?? "",
    supplier_product_description: product.supplier_product_description ?? "",
    supplier_warranty_months: product.supplier_warranty_months ? String(product.supplier_warranty_months) : "",
    net_weight_kg: product.net_weight_kg ? String(product.net_weight_kg) : "",
    gross_weight_kg: product.gross_weight_kg ? String(product.gross_weight_kg) : "",
    width_cm: product.width_cm ? String(product.width_cm) : "",
    height_cm: product.height_cm ? String(product.height_cm) : "",
    depth_cm: product.depth_cm ? String(product.depth_cm) : "",
    volumes: product.volumes ? String(product.volumes) : "",
    is_variation: Number(product.is_variation ?? 0),
    parent_code: product.parent_code ?? "",
    product_condition: product.product_condition ?? "",
    tags: product.tags ?? "",
    tags_group: product.tags_group ?? "",
  };
}