import type { ProductFormState } from "../types/products.types";
import type { LocalProductPayload } from "../types/products.types";
import { centsFromMoney } from "./centsFromMoney";

export function toPayload(form: ProductFormState): LocalProductPayload {
  return {
    name: form.name.trim(),
    sale_price_cents: centsFromMoney(form.sale_price),
    cost_price_cents: centsFromMoney(form.cost_price || "0"),
    purchase_price_cents: centsFromMoney(form.purchase_price || "0"),
    sku: form.sku || null,
    barcode: form.barcode || null,
    category_id: form.category_id || null,
    unit: form.unit || "UN",
    minimum_stock: Number(form.minimum_stock || 0),
    maximum_stock: form.maximum_stock.trim() ? Number(form.maximum_stock) : null,
    current_stock: Number(form.current_stock || 0),
    active: form.active,
    ncm: form.ncm || null,
    cfop: form.cfop || null,
    origin: form.origin || null,
    cest: form.cest || null,
    notes: form.notes || null,
    situation: form.situation || null,
    supplier_code: form.supplier_code || null,
    supplier_name: form.supplier_name || null,
    location: form.location || null,
    brand: form.brand || null,
    product_group: form.product_group || null,
    short_description: form.short_description || null,
    complementary_description: form.complementary_description || null,
    additional_info: form.additional_info || null,
    department: form.department || null,
    item_type: form.item_type || "Produto",
    expiration_date: form.expiration_date || null,
    items_per_box: form.items_per_box ? Number(form.items_per_box) : null,
    packaging_barcode: form.packaging_barcode || null,
    production_type: form.production_type || null,
    ipi_tax_class: form.ipi_tax_class || null,
    fci_number: form.fci_number || null,
    supplier_product_description: form.supplier_product_description || null,
    supplier_warranty_months: form.supplier_warranty_months ? Number(form.supplier_warranty_months) : null,
    net_weight_kg: form.net_weight_kg ? Number(form.net_weight_kg) : null,
    gross_weight_kg: form.gross_weight_kg ? Number(form.gross_weight_kg) : null,
    width_cm: form.width_cm ? Number(form.width_cm) : null,
    height_cm: form.height_cm ? Number(form.height_cm) : null,
    depth_cm: form.depth_cm ? Number(form.depth_cm) : null,
    volumes: form.volumes ? Number(form.volumes) : null,
    is_variation: form.is_variation,
    parent_code: form.parent_code || null,
    product_condition: form.product_condition || null,
    tags: form.tags || null,
    tags_group: form.tags_group || null,
  };
}